### ISSUE TITLE
ZipFile objects are not automatically disposed after use

### ISSUE THREAD

**Issue by pushedx** [mono/mono-addins#55]
There are instances of `new ZipFile` being used in Mono.Addins.Setup that are not automatically disposed, causing file handles to be held much longer than necessary.

AddinPackage.cs (93)
AddinPackage.cs (137) <- This one is fine because the FileStream is disposed, but for the sake of consistency
SetupService.cs (584)

(Lines as of commit 70e9d43008cae0cc9e318828de754cc8cbb724df)

This is an issue when you want to cleanup mpacks after `SetupService.Install` is called, but have to wait until the ZipFile handles get disposed (or the application exits), which is undesirable.

**Comment by mhutch** [comment]
Thanks! This was fixed in b54859fee98c71c0993e1211f9b6c27070054d9d
