### ISSUE TITLE
Mono-Addins 1.3.5 make install rule is failing

### ISSUE THREAD

**Issue by bmgandre** [mono/mono-addins#73]
Version 1.3.5 is building correctly but failing to install:

```
root@darkstar:/tmp/slackbuilds/mono-addins/mono-addins-c636f258d0a724e7c0de447ea717d18cb90bfb17# make DESTDIR=/tmp/package-mono-addins install
Making install in Mono.Addins
make[1]: Entering directory '/tmp/slackbuilds/mono-addins/mono-addins-c636f258d0a724e7c0de447ea717d18cb90bfb17/Mono.Addins'
make[2]: Entering directory '/tmp/slackbuilds/mono-addins/mono-addins-c636f258d0a724e7c0de447ea717d18cb90bfb17/Mono.Addins'
/usr/bin/gacutil /i ../bin/Mono.Addins.dll /f /package mono-addins /root /tmp/package-mono-addins/usr/local/lib || exit 1;
Failure adding assembly ../bin/Mono.Addins.dll to the cache: Strong name cannot be verified for delay-signed assembly
Makefile:552: recipe for target 'gac-install' failed
make[2]: *** [gac-install] Error 1
make[2]: Leaving directory '/tmp/slackbuilds/mono-addins/mono-addins-c636f258d0a724e7c0de447ea717d18cb90bfb17/Mono.Addins'
Makefile:429: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/tmp/slackbuilds/mono-addins/mono-addins-c636f258d0a724e7c0de447ea717d18cb90bfb17/Mono.Addins'
Makefile:350: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

Note that DESTDIR is used for linux packing.

**Comment by malahx** [comment]
Hello, I experienced the same issue on Arch Linux (and this issue seems to be duplicated with #70 ).

Nothing new? I saw that makefile/configure/autogen.sh have been deleted on the last release, is there an other way to compile this?

Thanks.

**Comment by mhutch** [comment]
Installing to the GAC is no longer supported. It's intended that apps should bundle their own copy of Mono.Addins, and obtain it from NuGet: https://www.nuget.org/packages/Mono.Addins

To build the NuGet packages, use `msbuild /t:Release`

**Comment by anthraxx** [comment]
@mhutch which really isn't a nice way for distributions. We aim to build things from source ourselves and not pull in precompiled binary dependencies from the internet. I'm sure there are a lot of people quite sad about this move

**Comment by mhutch** [comment]
It's not that difficult to build from source.

Check out this repo, and run `MSBuild /p:Configuration=Release`, and it will build nupkg packages and place then in the `bin` subdirectory.

In the project from which you want to use this, add a `nuget.config` file to add the newly built packages as a package source.

```xml
<configuration>
<packageSources>
<add key="Mono.Addins Source Build" value="/path/to/mono-addins/bin" />
</packageSources>
</configuration>
```

**Comment by Russtopia** [comment]
Well, I guess I'll give it a second chance then :). Thank you for the tip.

**Comment by kyrios123** [comment]
Also the [README](https://github.com/mono/mono-addins/blob/master/README) still provides instruction for building with the autotools.
